---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
library("mvarVis")
library("ade4")
```

## pca

```{r}
data(deug)
deug_pca <- ordinate(deug$tab, rows_annot = data.frame(res = deug$result),
                       method = "pca", scannf = F)
plot_mvar(deug_pca, list(list(), list(point = F, text = T, arrow = T)), col = "res",
          label = "label")
```

## acm

```{r}
data(banque)
banque_acm <- ordinate(banque[, -c(1:4)], rows_annot = banque[, 1:4],
                       method = "acm", scannf = F)
plot_mvar(gp1_acm, col = "age")
```

## coa

```{r}
data(bordeaux)
bordeaux_coa <- ordinate(bordeaux, method = "coa", scannf = F)
layers_list <- list(list(text = T, point = F), list(text = T, point = F))
plot_mvar(bordeaux_coa, label = "label", layers_list)
```

## fpca

```{r}
data(bsetal97)
w <- prep.fuzzy.var(bsetal97$biol, bsetal97$biol.blo)
bsetal_fpca <- ordinate(w, method = "fpca", rows_annot = data.frame(species = bsetal97$species.names), scannf = F)
plot_mvar(bsetal_fpca, label = "species", layers_list = list(list(text = T), list()))
```

## hillsmith

```{r}
data(dunedata)
attributes(dunedata$envir$use)$class <- "factor"
dunedata_hillsmith <- ordinate(dunedata$envir, method = "hillsmith", 
                               rows_annot = dunedata$veg, scannf = F)
plot_mvar(dunedata_hillsmith, col = "Ach.mil")
```

## mix

```{r}
data(dunedata)
dunedata_mix <- ordinate(dunedata$envir, method = "mix", 
                         rows_annot = dunedata$veg, scannf = F)
plot_mvar(dunedata_mix, col = "Ach.mil")
```

## nsc

```{r}
data(housetasks)
housetasks_nsc <- ordinate(housetasks, method = "nsc", scannf = F)
plot_mvar(housetasks_nsc, list(list(text = T, point = F), list(text = T, point = F, arrow = T)), label = "label")
```
